---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(ggplot2)
library(ggpubr)
library(readr)
library(dplyr)
library(ggthemes) 
library(scales) 
library(plotly)


```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
pub_211 <- read.csv("/Users/mawenting/Downloads/pub_211.csv")

#按学校统计各年发文量
pubnum_w <- pub_211 %>% 
  group_by(inst_cn,pubyear) %>% 
  summarise(pubnum_wos = sum(pubnum_wos)) 

# 选出2022年发文最多的十所学校
top10 <- pub_211 %>% 
  filter(pubyear == 2022) %>% 
  group_by(inst_cn) %>% 
  summarise(pubnum_wos = sum(pubnum_wos)) %>% 
  arrange(desc(pubnum_wos)) %>% 
  slice(1:10)

#筛选top10学校的数据并计算各年发文量
top10_pub <- pub_211 %>% 
  semi_join(top10,by = "inst_cn") %>% 
  group_by(inst_cn,pubyear) %>% 
  summarise(pubnum_wos = sum(pubnum_wos),
            totaljif = sum(totaljif))

#1 随时间变化top10学校发文散点图
 
  p2 <- ggplot(top10_pub, aes(x = pubyear, y = pubnum_wos)) + 
  geom_point(shape = 1, size = 2.5,aes(color = inst_cn)) + 
  theme(legend.text = element_text(family='SimSun')) +
  geom_smooth(method = "lm",color = "darkred", 
              formula = y~ poly(x, 2),
              se = FALSE) + 
  scale_x_continuous(limits = c(1996,2023),
                     breaks = seq(1995,2022,5)) +
  scale_y_continuous(breaks = seq(10000,60000,10000), 
                     limits = c(0,65000))+
  guides(colour = guide_legend(title = element_blank()), 
         linetype = guide_legend(title = element_blank()))+
  theme_classic() +
  labs(title = "1996-2022年Top10大学发文量散点图", 
       caption = "注：Top10指2022年发文量前十")
  ggplotly(p2,height = 400)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
  ggplot(top10_pub, aes(x = pubyear, y = pubnum_wos)) + 
  geom_point() + 
  theme(text = element_text(family='SimSun')) +
  geom_smooth(method = 'loess' ,formula = 'y ~ x',size = 0.3) +
  facet_wrap(~ inst_cn)+
  theme_classic() 
```



